name: ets_project
description: "ETS Project Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  path: ^1.9.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
